"""Add priority table

Revision ID: a2b093128ac0
Revises: 8183b90da31e
Create Date: 2026-02-28 17:42:07.749807

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2b093128ac0"
down_revision: Union[str, Sequence[str], None] = "8183b90da31e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "priority",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("todos", sa.Column("priority_id", sa.Integer()))

    op.execute(sa.text('UPDATE "todos" SET PRIORITY_ID = PRIORITY'))
    op.execute("""
        INSERT INTO priority (id, name) VALUES
        (1, 'lowest'),
        (2, 'low'),
        (3, 'normal'),
        (4, 'high'),
        (5, 'highest')
        """)

    op.alter_column("todos", "priority_id", nullable=False)
    op.create_foreign_key(None, "todos", "priority", ["priority_id"], ["id"])
    op.drop_column("todos", "priority")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos",
        sa.Column("priority", sa.INTEGER(), autoincrement=False),
    )
    op.execute(sa.text('UPDATE "todos" SET PRIORITY = PRIORITY_ID'))
    op.alter_column("todos", "priority", nullable=False)
    op.drop_constraint("todos_priority_id_fkey", "todos", type_="foreignkey")
    op.drop_column("todos", "priority_id")
    op.drop_table("priority")
    # ### end Alembic commands ###
